# The name of this app. Must be unique within a project.
name: "blog_project"

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application.
type: 'python:3.12'

# Define the web service
web:
    type: 'python:3.12'
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET blog_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

# The size of the persistent disk of the application (in MB).
disk: 2048

# Define mounts
mounts:
    "logs":
        source: local
        source_path: logs

hooks:
  build: |
    pipenv install --system --deploy
    # Collect static files
    python manage.py collectstatic --noinput
    # Install dependencies
    pip install -r requirements.txt
    pip install -r requirements_remote.txt

  deploy: |
    # Migrate the database
    python manage.py migrate
