name: "blog_project"
type: "python:3.10"

relationships:
    database: "db:postgresql"

# Configuration for the web application
web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET blog_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

# Disk size configuration
disk: 1024

# Configuration for log mounts
mounts:
    "logs":
        source: local
        source_path: logs

# Hooks for lifecycle events
hooks:
    build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        
        mkdir logs
        python manage.py collectstatic --noinput
        rm -rf logs
    deploy: |
        python manage.py migrate
